identifier: tk44
name: tk44
type: keyboard
url: https://github.com/Ladniy/TK44
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - gpio
